#!/usr/bin/env python
import airship

import os
import sys
try:
    import argparse
except ImportError:
    argparse = False

from groundstation.node import Node
from groundstation.station import Station

myself = Node()
station_path = os.path.expanduser("~/.groundstation")
station = Station(station_path, myself)


class FakeConfig(object):
    def __init__(self):
        self.host = 'localhost'

    def parse_args(self, *args):
        return self


def _create_option_parser():
    if not argparse:
        return FakeConfig()
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", dest='host', action='store')
    return parser


def main(argv):
    parser = _create_option_parser()
    args = parser.parse_args(argv[1:])
    app = airship.make_airship(station)
    app.run(args.host, 9005, True)

if __name__ == "__main__":
    main(sys.argv)
