#!/usr/bin/env python
import airship

import sys
import argparse

from groundstation.node import Node
from groundstation.station import Station

myself = Node()
station = Station.from_env(myself)


def _create_option_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", dest='host', action='store')
    return parser


def main(argv):
    parser = _create_option_parser()
    args = parser.parse_args(argv[1:])
    app = airship.make_airship(station)
    app.run(args.host, 9005, True)

if __name__ == "__main__":
    main(sys.argv)
