#!/usr/bin/env python
import os
import sys
import select
import time
import argparse
from groundstation import logger
log = logger.getLogger("soundstationd")

from groundstation.node import Node
from groundstation.station import Station

from groundstation.audio_shrieker import AudioShrieker
from groundstation.audio_announcer import AudioAnnouncer
from groundstation.audio_discoverer import AudioDiscoverer
from groundstation.audio_receiver import AudioReceiver
from groundstation import settings

import groundstation.audio

BEACON_TIMEOUT = groundstation.audio.BEACON_TIMEOUT
TONES = groundstation.audio.TONES

myself = Node()
station = Station.from_env(myself)

AUDIO = groundstation.audio.audio_singleton

def main_server(opts):
    receiver = AudioReceiver(TONES, station)
    log.info("Starting discoverer at %d:%d:%dhz" % tuple(sorted(TONES.values())))
    receiver.start_listening()

def main_client(opts):
    shrieker  = AudioShrieker(TONES, AUDIO)
    log.info("Starting shrieker at %d:%d:%dhz" % tuple(sorted(TONES.values())))
    shrieker.shriek(station)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--server", dest='server', action='store_true',
                        default=None)
    parser.add_argument("--client", dest='server', action='store_false',
                        default=None)

    args = parser.parse_args()
    if args.server is None:
        raise Exception("Must specify --server or --client")

    if args.server:
        main_server(args)
    else:
        main_client(args)
