# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='groundstation/proto/channel_list.proto',
  package='',
  serialized_pb='\n&groundstation/proto/channel_list.proto\"\"\n\x0b\x43hannelList\x12\x13\n\x0b\x63hannelname\x18\x01 \x03(\t')




_CHANNELLIST = descriptor.Descriptor(
  name='ChannelList',
  full_name='ChannelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channelname', full_name='ChannelList.channelname', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['ChannelList'] = _CHANNELLIST

class ChannelList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHANNELLIST
  
  # @@protoc_insertion_point(class_scope:ChannelList)

# @@protoc_insertion_point(module_scope)
