# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groundstation/proto/channel_list.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='groundstation/proto/channel_list.proto',
  package='',
  serialized_pb='\n&groundstation/proto/channel_list.proto\"\xdb\x02\n\x0b\x43hannelList\x12\x31\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x1f.ChannelList.ChannelDescription\x1a\x98\x02\n\x12\x43hannelDescription\x12\x13\n\x0b\x63hannelname\x18\x01 \x02(\t\x12\x45\n\x05grefs\x18\x02 \x03(\x0b\x32\x36.ChannelList.ChannelDescription.ChannelGrefDescription\x1a\xa5\x01\n\x16\x43hannelGrefDescription\x12\x12\n\nidentifier\x18\x01 \x02(\t\x12L\n\x04tips\x18\x02 \x03(\x0b\x32>.ChannelList.ChannelDescription.ChannelGrefDescription.GrefTip\x1a)\n\x07GrefTip\x12\x0b\n\x03tip\x18\x01 \x02(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c')




_CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION_GREFTIP = _descriptor.Descriptor(
  name='GrefTip',
  full_name='ChannelList.ChannelDescription.ChannelGrefDescription.GrefTip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tip', full_name='ChannelList.ChannelDescription.ChannelGrefDescription.GrefTip.tip', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='ChannelList.ChannelDescription.ChannelGrefDescription.GrefTip.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=349,
  serialized_end=390,
)

_CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION = _descriptor.Descriptor(
  name='ChannelGrefDescription',
  full_name='ChannelList.ChannelDescription.ChannelGrefDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='ChannelList.ChannelDescription.ChannelGrefDescription.identifier', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tips', full_name='ChannelList.ChannelDescription.ChannelGrefDescription.tips', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION_GREFTIP, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=225,
  serialized_end=390,
)

_CHANNELLIST_CHANNELDESCRIPTION = _descriptor.Descriptor(
  name='ChannelDescription',
  full_name='ChannelList.ChannelDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channelname', full_name='ChannelList.ChannelDescription.channelname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grefs', full_name='ChannelList.ChannelDescription.grefs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=110,
  serialized_end=390,
)

_CHANNELLIST = _descriptor.Descriptor(
  name='ChannelList',
  full_name='ChannelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='ChannelList.channels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHANNELLIST_CHANNELDESCRIPTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=390,
)

_CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION_GREFTIP.containing_type = _CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION;
_CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION.fields_by_name['tips'].message_type = _CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION_GREFTIP
_CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION.containing_type = _CHANNELLIST_CHANNELDESCRIPTION;
_CHANNELLIST_CHANNELDESCRIPTION.fields_by_name['grefs'].message_type = _CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION
_CHANNELLIST_CHANNELDESCRIPTION.containing_type = _CHANNELLIST;
_CHANNELLIST.fields_by_name['channels'].message_type = _CHANNELLIST_CHANNELDESCRIPTION
DESCRIPTOR.message_types_by_name['ChannelList'] = _CHANNELLIST

class ChannelList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class ChannelDescription(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType

    class ChannelGrefDescription(_message.Message):
      __metaclass__ = _reflection.GeneratedProtocolMessageType

      class GrefTip(_message.Message):
        __metaclass__ = _reflection.GeneratedProtocolMessageType
        DESCRIPTOR = _CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION_GREFTIP

        # @@protoc_insertion_point(class_scope:ChannelList.ChannelDescription.ChannelGrefDescription.GrefTip)
      DESCRIPTOR = _CHANNELLIST_CHANNELDESCRIPTION_CHANNELGREFDESCRIPTION

      # @@protoc_insertion_point(class_scope:ChannelList.ChannelDescription.ChannelGrefDescription)
    DESCRIPTOR = _CHANNELLIST_CHANNELDESCRIPTION

    # @@protoc_insertion_point(class_scope:ChannelList.ChannelDescription)
  DESCRIPTOR = _CHANNELLIST

  # @@protoc_insertion_point(class_scope:ChannelList)


# @@protoc_insertion_point(module_scope)
