# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groundstation/proto/gizmo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='groundstation/proto/gizmo.proto',
  package='',
  serialized_pb='\n\x1fgroundstation/proto/gizmo.proto\"\x9f\x01\n\x05Gizmo\x12\n\n\x02id\x18\x01 \x02(\t\x12\x11\n\tstationid\x18\x02 \x02(\t\x12\x1e\n\x04type\x18\x03 \x02(\x0e\x32\x10.Gizmo.GizmoType\x12\x0c\n\x04verb\x18\x04 \x02(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\"8\n\tGizmoType\x12\x0b\n\x07REQUEST\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x12\x10\n\x0cNOTIFICATION\x10\x02')



_GIZMO_GIZMOTYPE = _descriptor.EnumDescriptor(
  name='GizmoType',
  full_name='Gizmo.GizmoType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTIFICATION', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=139,
  serialized_end=195,
)


_GIZMO = _descriptor.Descriptor(
  name='Gizmo',
  full_name='Gizmo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Gizmo.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stationid', full_name='Gizmo.stationid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Gizmo.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verb', full_name='Gizmo.verb', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='Gizmo.payload', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GIZMO_GIZMOTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=195,
)

_GIZMO.fields_by_name['type'].enum_type = _GIZMO_GIZMOTYPE
_GIZMO_GIZMOTYPE.containing_type = _GIZMO;
DESCRIPTOR.message_types_by_name['Gizmo'] = _GIZMO

class Gizmo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GIZMO

  # @@protoc_insertion_point(class_scope:Gizmo)


# @@protoc_insertion_point(module_scope)
