# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groundstation/proto/object_list.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='groundstation/proto/object_list.proto',
  package='',
  serialized_pb='\n%groundstation/proto/object_list.proto\" \n\nObjectList\x12\x12\n\nobjectname\x18\x01 \x03(\t')




_OBJECTLIST = _descriptor.Descriptor(
  name='ObjectList',
  full_name='ObjectList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objectname', full_name='ObjectList.objectname', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['ObjectList'] = _OBJECTLIST

class ObjectList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OBJECTLIST

  # @@protoc_insertion_point(class_scope:ObjectList)


# @@protoc_insertion_point(module_scope)
