# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='groundstation/proto/request.proto',
  package='',
  serialized_pb='\n!groundstation/proto/request.proto\"~\n\x07Request\x12\n\n\x02id\x18\x01 \x02(\t\x12\"\n\x04verb\x18\x02 \x02(\x0e\x32\x14.Request.RequestType\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"2\n\x0bRequestType\x12\x12\n\x0eLISTALLOBJECTS\x10\x00\x12\x0f\n\x0b\x46\x45TCHOBJECT\x10\x01')



_REQUEST_REQUESTTYPE = descriptor.EnumDescriptor(
  name='RequestType',
  full_name='Request.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='LISTALLOBJECTS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FETCHOBJECT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=113,
  serialized_end=163,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Request.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='verb', full_name='Request.verb', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='Request.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_REQUESTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=163,
)

_REQUEST.fields_by_name['verb'].enum_type = _REQUEST_REQUESTTYPE
_REQUEST_REQUESTTYPE.containing_type = _REQUEST;
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:Request)

# @@protoc_insertion_point(module_scope)
