# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='groundstation/proto/response.proto',
  package='',
  serialized_pb='\n\"groundstation/proto/response.proto\"\x8f\x01\n\x08Response\x12\n\n\x02id\x18\x01 \x02(\t\x12$\n\x04verb\x18\x02 \x02(\x0e\x32\x16.Response.ResponseType\x12\x0f\n\x07payload\x18\x03 \x02(\x0c\"@\n\x0cResponseType\x12\r\n\tTERMINATE\x10\x00\x12\x0c\n\x08TRANSFER\x10\x01\x12\x13\n\x0f\x44\x45SCRIBEOBJECTS\x10\x02')



_RESPONSE_RESPONSETYPE = descriptor.EnumDescriptor(
  name='ResponseType',
  full_name='Response.ResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='TERMINATE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRANSFER', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DESCRIBEOBJECTS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=118,
  serialized_end=182,
)


_RESPONSE = descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Response.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='verb', full_name='Response.verb', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='Response.payload', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_RESPONSETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=182,
)

_RESPONSE.fields_by_name['verb'].enum_type = _RESPONSE_RESPONSETYPE
_RESPONSE_RESPONSETYPE.containing_type = _RESPONSE;
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

class Response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE
  
  # @@protoc_insertion_point(class_scope:Response)

# @@protoc_insertion_point(module_scope)
