#!/usr/bin/env python
import os
import sys

from groundstation.station import Station

def main(argv):
    station = Station.from_env(None)

    for channel in station.channels():
        print(channel)
        print("=" * len(channel))
        print("")

        for gref in station.grefs(channel):
            print("- %s" % gref)
        print ""

if __name__ == '__main__':
    main(sys.argv)
